baseURL: http://ghoscht.github.io/
languageCode: en-us
title: GHOSCHT
theme: papermod
enableRobotsTXT: true
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: posts
      name: Posts
      url: /posts
      weight: 2      
    - name: Search
      url: search/
      weight: 10
    - name: Categories
      url: categories/
      weight: 10
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  profileMode:
      enabled: true
      title: Hey, I'm GHOSCHT
      subtitle: CompSci Student @TUM | electronics | VR enthusiast
      buttons:
        - name: Posts
          url: /posts
        - name: Projects
          url: /tags/project       

  socialIcons:
    - name: github
      url: "https://github.com/GHOSCHT"   
    - name: instagram
      url: "https://www.instagram.com/gh0scht/"
    - name: twitter
      url: "https://twitter.com/GHOSCHT"   
    - name: steam
      url: "https://steamcommunity.com/id/ghoscht/"         
    - name: Key
      url: "https://github.com/GHOSCHT.gpg"
    - name: Discord
      url: "https://discord.com/users/244761751294443520"      
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
